### ISSUE TITLE
Adopt a tool for managing colour of console text

### ISSUE THREAD

**Issue by shirakaba** [shirakaba/cocoapojs#5]
So far we're using Node.js primitives, but it's kinda gross so we should migrate to something like `chalk` (or better).

**Comment by webdiscus** [comment]
@shirakaba,

`ansis` has few stars on GitHub because this package has very few visitors on GitHub.
Perhaps most developers uses already "old school" packages, like `chalk` since 10-5-3 years and do not need new ones.

P.S. You can see the [features comparison](https://github.com/shirakaba/cocoapojs/issues/5#compare) and [benchmarks](https://github.com/shirakaba/cocoapojs/issues/5#benchmark) of most popular terminal colors libraries:
[ansis](https://github.com/webdiscus/ansis), [chalk](https://github.com/chalk/chalk), [kleur](https://github.com/lukeed/kleur), [kolorist](https://github.com/marvinhagemeister/kolorist), [colors.js](https://github.com/Marak/colors.js), [colorette](https://github.com/jorgebucaran/colorette), [picocolors](https://github.com/alexeyraspopov/picocolors), [ansi-colors](https://github.com/doowb/ansi-colors), [cli-color](https://github.com/medikoo/cli-color), [colors-cli](https://github.com/jaywcjlove/colors-cli)

**Comment by webdiscus** [comment]
> A bunch of other competitors compared [here](https://github.com/webdiscus/ansis?tab=readme-ov-file#comparison-of-most-popular-libraries) (on ansis's docs). The comparison is a bit out of date, as kleur now supports nested strings, too.

To be fair, I'd like to point out that Kleur does not support nested template strings.

For example, this doesn't works:

```js
import kleur from 'kleur';
console.log( kleur.red`R ${kleur.green`G ${kleur.blue`B`} G`} R`);
```

Outputs:

![Image](https://github.com/user-attachments/assets/13b7c3f7-56d0-40c6-b778-d42fba55bbfd)

In any case, I respect your choice. Kleur is a good library.
